### PR TITLE
Great scenario, work done.

### PR DESCRIPTION
**Pull request by astrohlicpu**
Please note that I didn't make a column to record if there is a accompanying disorder, as we can just check if the desc is null. 
Let me know if you want any changes.

### CODE REVIEW

**Comment by pessyfeder** [comment]
Just finished looking over your work. Looks perfect! Thank you!
I was just wondering about a few things.

1: In the table, the check constraint on the Gender column was not named.
Was that intentional? What are the effects of that?

2 I noticed that when you used the 'getdate' function in a check
constraint, you converted it to a date data type. Why?

3 Do the Emergency Contact Phone Number columns need unique constraints?

I would appreciate it if you could clarify these things for me. Thank you
again!

**Comment by astrohlicpu** [comment]
1.  Not naming the constraint was by mistake. The effect would be, that when the constraint would be violated, I would get a random message, and it would be hard to figure out what went wrong. You can try it and see.

2. The get date returns a datetime not a date. I think that if you don't convert then sql server would convert it automatically when it gets compared to a date, so I don't think it actually makes a difference now that you are pointing it out...

3. I guess it would make sense didn't think about it.

Let me know if you have any other questions on this.

**Comment by pessyfeder** [comment]
Got it; thanks.

**Comment by pessyfeder** [comment]
Upon further review of the Clients table you built based on my business spec, something caught my attention. In the Phone columns, you formatted the check constraints like this: [1-9]... for each digit. Would that create a conflict if a phone number containing a zero were to be entered?

**Comment by astrohlicpu** [comment]
You are correct. It is a copy paste error. I intended to make the first one as [1-9] as no number starts with 0, but the others where supposed to be [0-9].
Thanks for pointing this out.

**Comment by pessyfeder** [comment]
Thanks for the clarification.

**Pull request merged**
